/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <stdint.h>		// Use the C99 official header


/* Put header files here or function declarations like below */
 #include "julia.h"
 

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1init(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  jl_init();
}


SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1init_1with_1image(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  jl_init_with_image((char const *)arg1,(char const *)arg2);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1get_1default_1sysimg_1path(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)jl_get_default_sysimg_path();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1is_1initialized(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)jl_is_initialized();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1atexit_1hook(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  jl_atexit_hook(arg1);
}


SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1exit(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  jl_exit(arg1);
}


SWIGEXPORT jstring JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1pathname_1for_1handle(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  void *arg1 = (void *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (char *)jl_pathname_for_handle(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1preload_1sysimg_1so(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  jl_preload_sysimg_so((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1set_1sysimg_1so(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  void *arg1 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  jl_set_sysimg_so(arg1);
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1create_1system_1image(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ios_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ios_t *)jl_create_system_image();
  *(ios_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1save_1system_1image(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  jl_save_system_image((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1restore_1system_1image(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  jl_restore_system_image((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1restore_1system_1image_1data(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  char *arg1 = (char *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  arg2 = (size_t)jarg2; 
  jl_restore_system_image_data((char const *)arg1,arg2);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jint JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1save_1incremental(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  jl_array_t *arg2 = (jl_array_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(jl_array_t **)&jarg2; 
  result = (int)jl_save_incremental((char const *)arg1,arg2);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1restore_1incremental(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  jl_array_t *arg2 = (jl_array_t *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(jl_array_t **)&jarg2; 
  result = (jl_value_t *)jl_restore_incremental((char const *)arg1,arg2);
  *(jl_value_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1restore_1incremental_1from_1buf(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  size_t arg2 ;
  jl_array_t *arg3 = (jl_array_t *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (size_t)jarg2; 
  arg3 = *(jl_array_t **)&jarg3; 
  result = (jl_value_t *)jl_restore_incremental_from_buf((char const *)arg1,arg2,arg3);
  *(jl_value_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1parse_1input_1line(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jstring jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  size_t arg2 ;
  char *arg3 = (char *) 0 ;
  size_t arg4 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (size_t)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (size_t)jarg4; 
  result = (jl_value_t *)jl_parse_input_line((char const *)arg1,arg2,(char const *)arg3,arg4);
  *(jl_value_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1parse_1string(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  size_t arg2 ;
  int arg3 ;
  int arg4 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (size_t)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (jl_value_t *)jl_parse_string((char const *)arg1,arg2,arg3,arg4);
  *(jl_value_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1load_1file_1string(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jstring jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  size_t arg2 ;
  char *arg3 = (char *) 0 ;
  jl_module_t *arg4 = (jl_module_t *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (size_t)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(jl_module_t **)&jarg4; 
  result = (jl_value_t *)jl_load_file_string((char const *)arg1,arg2,arg3,arg4);
  *(jl_value_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1expand(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  jl_module_t *arg2 = (jl_module_t *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  arg2 = *(jl_module_t **)&jarg2; 
  result = (jl_value_t *)jl_expand(arg1,arg2);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1expand_1stmt(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  jl_module_t *arg2 = (jl_module_t *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  arg2 = *(jl_module_t **)&jarg2; 
  result = (jl_value_t *)jl_expand_stmt(arg1,arg2);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1eval_1string(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (jl_value_t *)jl_eval_string((char const *)arg1);
  *(jl_value_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1new_1bits(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  void *arg2 = (void *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  result = (jl_value_t *)jl_new_bits(arg1,arg2);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1new_1struct(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  jl_datatype_t *arg1 = (jl_datatype_t *) 0 ;
  void *arg2 = 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_datatype_t **)&jarg1; 
  result = (jl_value_t *)jl_new_struct(arg1,arg2);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1new_1structv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  jl_datatype_t *arg1 = (jl_datatype_t *) 0 ;
  jl_value_t **arg2 = (jl_value_t **) 0 ;
  uint32_t arg3 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_datatype_t **)&jarg1; 
  arg2 = *(jl_value_t ***)&jarg2; 
  arg3 = (uint32_t)jarg3; 
  result = (jl_value_t *)jl_new_structv(arg1,arg2,arg3);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1new_1struct_1uninit(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  jl_datatype_t *arg1 = (jl_datatype_t *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_datatype_t **)&jarg1; 
  result = (jl_value_t *)jl_new_struct_uninit(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1new_1method_1instance_1uninit(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  jl_method_instance_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (jl_method_instance_t *)jl_new_method_instance_uninit();
  *(jl_method_instance_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1svec(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  void *arg2 = 0 ;
  jl_svec_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  result = (jl_svec_t *)jl_svec(arg1,arg2);
  *(jl_svec_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1svec1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  jl_svec_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (jl_svec_t *)jl_svec1(arg1);
  *(jl_svec_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1svec2(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  void *arg2 = (void *) 0 ;
  jl_svec_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  result = (jl_svec_t *)jl_svec2(arg1,arg2);
  *(jl_svec_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1alloc_1svec(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  jl_svec_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  result = (jl_svec_t *)jl_alloc_svec(arg1);
  *(jl_svec_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1alloc_1svec_1uninit(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  jl_svec_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  result = (jl_svec_t *)jl_alloc_svec_uninit(arg1);
  *(jl_svec_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1svec_1copy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  jl_svec_t *arg1 = (jl_svec_t *) 0 ;
  jl_svec_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_svec_t **)&jarg1; 
  result = (jl_svec_t *)jl_svec_copy(arg1);
  *(jl_svec_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1svec_1fill(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  size_t arg1 ;
  jl_value_t *arg2 = (jl_value_t *) 0 ;
  jl_svec_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  arg2 = *(jl_value_t **)&jarg2; 
  result = (jl_svec_t *)jl_svec_fill(arg1,arg2);
  *(jl_svec_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1tupletype_1fill(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  size_t arg1 ;
  jl_value_t *arg2 = (jl_value_t *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  arg2 = *(jl_value_t **)&jarg2; 
  result = (jl_value_t *)jl_tupletype_fill(arg1,arg2);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1symbol(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  jl_sym_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (jl_sym_t *)jl_symbol((char const *)arg1);
  *(jl_sym_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1symbol_1lookup(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  jl_sym_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (jl_sym_t *)jl_symbol_lookup((char const *)arg1);
  *(jl_sym_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1symbol_1n(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  size_t arg2 ;
  jl_sym_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (size_t)jarg2; 
  result = (jl_sym_t *)jl_symbol_n((char const *)arg1,arg2);
  *(jl_sym_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1gensym(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  jl_sym_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (jl_sym_t *)jl_gensym();
  *(jl_sym_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1tagged_1gensym(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int32_t arg2 ;
  jl_sym_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (int32_t)jarg2; 
  result = (jl_sym_t *)jl_tagged_gensym((char const *)arg1,arg2);
  *(jl_sym_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1get_1root_1symbol(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  jl_sym_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (jl_sym_t *)jl_get_root_symbol();
  *(jl_sym_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1generic_1function_1def(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  jl_sym_t *arg1 = (jl_sym_t *) 0 ;
  jl_module_t *arg2 = (jl_module_t *) 0 ;
  jl_value_t **arg3 = (jl_value_t **) 0 ;
  jl_value_t *arg4 = (jl_value_t *) 0 ;
  jl_binding_t *arg5 = (jl_binding_t *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_sym_t **)&jarg1; 
  arg2 = *(jl_module_t **)&jarg2; 
  arg3 = *(jl_value_t ***)&jarg3; 
  arg4 = *(jl_value_t **)&jarg4; 
  arg5 = *(jl_binding_t **)&jarg5; 
  result = (jl_value_t *)jl_generic_function_def(arg1,arg2,arg3,arg4,arg5);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1method_1def(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jl_svec_t *arg1 = (jl_svec_t *) 0 ;
  jl_code_info_t *arg2 = (jl_code_info_t *) 0 ;
  jl_module_t *arg3 = (jl_module_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_svec_t **)&jarg1; 
  arg2 = *(jl_code_info_t **)&jarg2; 
  arg3 = *(jl_module_t **)&jarg3; 
  jl_method_def(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1code_1for_1staged(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  jl_method_instance_t *arg1 = (jl_method_instance_t *) 0 ;
  jl_code_info_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_method_instance_t **)&jarg1; 
  result = (jl_code_info_t *)jl_code_for_staged(arg1);
  *(jl_code_info_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1copy_1code_1info(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  jl_code_info_t *arg1 = (jl_code_info_t *) 0 ;
  jl_code_info_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_code_info_t **)&jarg1; 
  result = (jl_code_info_t *)jl_copy_code_info(arg1);
  *(jl_code_info_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1get_1world_1counter(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  result = jl_get_world_counter();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1get_1kwsorter(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  jl_function_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (jl_function_t *)jl_get_kwsorter(arg1);
  *(jl_function_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1bool(JNIEnv *jenv, jclass jcls, jbyte jarg1) {
  jlong jresult = 0 ;
  int8_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int8_t)jarg1; 
  result = (jl_value_t *)jl_box_bool(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1int8(JNIEnv *jenv, jclass jcls, jbyte jarg1) {
  jlong jresult = 0 ;
  int8_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int8_t)jarg1; 
  result = (jl_value_t *)jl_box_int8(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1uint8(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jlong jresult = 0 ;
  uint8_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (uint8_t)jarg1; 
  result = (jl_value_t *)jl_box_uint8(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1int16(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jlong jresult = 0 ;
  int16_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int16_t)jarg1; 
  result = (jl_value_t *)jl_box_int16(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1uint16(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  uint16_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (uint16_t)jarg1; 
  result = (jl_value_t *)jl_box_uint16(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1int32(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int32_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int32_t)jarg1; 
  result = (jl_value_t *)jl_box_int32(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1uint32(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  uint32_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (uint32_t)jarg1; 
  result = (jl_value_t *)jl_box_uint32(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1char(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  uint32_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (uint32_t)jarg1; 
  result = (jl_value_t *)jl_box_char(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1int64(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  int64_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int64_t)jarg1; 
  result = (jl_value_t *)jl_box_int64(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1uint64(JNIEnv *jenv, jclass jcls, jobject jarg1) {
  jlong jresult = 0 ;
  uint64_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    jclass clazz;
    jmethodID mid;
    jbyteArray ba;
    jbyte* bae;
    jsize sz;
    int i;
    
    if (!jarg1) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "BigInteger null");
      return 0;
    }
    clazz = (*jenv)->GetObjectClass(jenv, jarg1);
    mid = (*jenv)->GetMethodID(jenv, clazz, "toByteArray", "()[B");
    ba = (jbyteArray)(*jenv)->CallObjectMethod(jenv, jarg1, mid);
    bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    sz = (*jenv)->GetArrayLength(jenv, ba);
    arg1 = 0;
    if (sz > 0) {
      arg1 = (uint64_t)(signed char)bae[0];
      for(i=1; i<sz; i++) {
        arg1 = (arg1 << 8) | (uint64_t)(unsigned char)bae[i];
      }
    }
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
  }
  result = (jl_value_t *)jl_box_uint64(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1float32(JNIEnv *jenv, jclass jcls, jfloat jarg1) {
  jlong jresult = 0 ;
  float arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  result = (jl_value_t *)jl_box_float32(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1float64(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  jlong jresult = 0 ;
  double arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  result = (jl_value_t *)jl_box_float64(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1voidpointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (jl_value_t *)jl_box_voidpointer(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1ssavalue(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  result = (jl_value_t *)jl_box_ssavalue(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1box_1slotnumber(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  jl_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  result = (jl_value_t *)jl_box_slotnumber(arg1);
  *(jl_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jbyte JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1bool(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jbyte jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  int8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (int8_t)jl_unbox_bool(arg1);
  jresult = (jbyte)result; 
  return jresult;
}


SWIGEXPORT jbyte JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1int8(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jbyte jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  int8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (int8_t)jl_unbox_int8(arg1);
  jresult = (jbyte)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1uint8(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (uint8_t)jl_unbox_uint8(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1int16(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  int16_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (int16_t)jl_unbox_int16(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1uint16(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  uint16_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (uint16_t)jl_unbox_uint16(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1int32(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  int32_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (int32_t)jl_unbox_int32(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1uint32(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (uint32_t)jl_unbox_uint32(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1int64(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  int64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (int64_t)jl_unbox_int64(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1uint64(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jobject jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (uint64_t)jl_unbox_uint64(arg1);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    (*jenv)->DeleteLocalRef(jenv, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1float32(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jfloat jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (float)jl_unbox_float32(arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1float64(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (double)jl_unbox_float64(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1unbox_1voidpointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  result = (void *)jl_unbox_voidpointer(arg1);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_julia_jni_swig_Julia4JJNI_jl_1get_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  jl_value_t *arg1 = (jl_value_t *) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jl_value_t **)&jarg1; 
  arg2 = *(size_t **)&jarg2; 
  result = (int)jl_get_size(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

