/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.julia.jni.swig;

public class Julia4J {
  public static String jl_get_libdir() {
    return Julia4JJNI.jl_get_libdir();
  }

  public static void jl_init() {
    Julia4JJNI.jl_init();
  }

  public static void jl_init_with_image(String julia_bindir, String image_path) {
    Julia4JJNI.jl_init_with_image(julia_bindir, image_path);
  }

  public static String jl_get_default_sysimg_path() {
    return Julia4JJNI.jl_get_default_sysimg_path();
  }

  public static int jl_is_initialized() {
    return Julia4JJNI.jl_is_initialized();
  }

  public static void jl_atexit_hook(int status) {
    Julia4JJNI.jl_atexit_hook(status);
  }

  public static void jl_exit(int status) {
    Julia4JJNI.jl_exit(status);
  }

  public static String jl_pathname_for_handle(SWIGTYPE_p_void handle) {
    return Julia4JJNI.jl_pathname_for_handle(SWIGTYPE_p_void.getCPtr(handle));
  }

  public static SWIGTYPE_p_p_jl_gcframe_t jl_adopt_thread() {
    long cPtr = Julia4JJNI.jl_adopt_thread();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_jl_gcframe_t(cPtr, false);
  }

  public static void jl_preload_sysimg_so(String fname) {
    Julia4JJNI.jl_preload_sysimg_so(fname);
  }

  public static void jl_set_sysimg_so(SWIGTYPE_p_void handle) {
    Julia4JJNI.jl_set_sysimg_so(SWIGTYPE_p_void.getCPtr(handle));
  }

  public static void jl_create_system_image(SWIGTYPE_p_p_void arg0, SWIGTYPE_p_jl_array_t worklist, SWIGTYPE_p_bool_t emit_split, SWIGTYPE_p_p_ios_t s, SWIGTYPE_p_p_ios_t z, SWIGTYPE_p_p_jl_array_t udeps, SWIGTYPE_p_long_long srctextpos) {
    Julia4JJNI.jl_create_system_image(SWIGTYPE_p_p_void.getCPtr(arg0), SWIGTYPE_p_jl_array_t.getCPtr(worklist), SWIGTYPE_p_bool_t.getCPtr(emit_split), SWIGTYPE_p_p_ios_t.getCPtr(s), SWIGTYPE_p_p_ios_t.getCPtr(z), SWIGTYPE_p_p_jl_array_t.getCPtr(udeps), SWIGTYPE_p_long_long.getCPtr(srctextpos));
  }

  public static void jl_restore_system_image(String fname) {
    Julia4JJNI.jl_restore_system_image(fname);
  }

  public static void jl_restore_system_image_data(String buf, long len) {
    Julia4JJNI.jl_restore_system_image_data(buf, len);
  }

  public static void jl_write_compiler_output() {
    Julia4JJNI.jl_write_compiler_output();
  }

  public static SWIGTYPE_p_jl_value_t jl_parse_all(String text, long text_len, String filename, long filename_len, long lineno) {
    long cPtr = Julia4JJNI.jl_parse_all(text, text_len, filename, filename_len, lineno);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_parse_string(String text, long text_len, int offset, int greedy) {
    long cPtr = Julia4JJNI.jl_parse_string(text, text_len, offset, greedy);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_expand(SWIGTYPE_p_jl_value_t expr, SWIGTYPE_p_jl_module_t inmodule) {
    long cPtr = Julia4JJNI.jl_expand(SWIGTYPE_p_jl_value_t.getCPtr(expr), SWIGTYPE_p_jl_module_t.getCPtr(inmodule));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_expand_with_loc(SWIGTYPE_p_jl_value_t expr, SWIGTYPE_p_jl_module_t inmodule, String file, int line) {
    long cPtr = Julia4JJNI.jl_expand_with_loc(SWIGTYPE_p_jl_value_t.getCPtr(expr), SWIGTYPE_p_jl_module_t.getCPtr(inmodule), file, line);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_expand_with_loc_warn(SWIGTYPE_p_jl_value_t expr, SWIGTYPE_p_jl_module_t inmodule, String file, int line) {
    long cPtr = Julia4JJNI.jl_expand_with_loc_warn(SWIGTYPE_p_jl_value_t.getCPtr(expr), SWIGTYPE_p_jl_module_t.getCPtr(inmodule), file, line);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_expand_stmt(SWIGTYPE_p_jl_value_t expr, SWIGTYPE_p_jl_module_t inmodule) {
    long cPtr = Julia4JJNI.jl_expand_stmt(SWIGTYPE_p_jl_value_t.getCPtr(expr), SWIGTYPE_p_jl_module_t.getCPtr(inmodule));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_expand_stmt_with_loc(SWIGTYPE_p_jl_value_t expr, SWIGTYPE_p_jl_module_t inmodule, String file, int line) {
    long cPtr = Julia4JJNI.jl_expand_stmt_with_loc(SWIGTYPE_p_jl_value_t.getCPtr(expr), SWIGTYPE_p_jl_module_t.getCPtr(inmodule), file, line);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_libhandle jl_load_dynamic_library(String fname, long flags, int throw_err) {
    return new SWIGTYPE_p_jl_libhandle(Julia4JJNI.jl_load_dynamic_library(fname, flags, throw_err), true);
  }

  public static SWIGTYPE_p_jl_libhandle jl_dlopen(String filename, long flags) {
    return new SWIGTYPE_p_jl_libhandle(Julia4JJNI.jl_dlopen(filename, flags), true);
  }

  public static int jl_dlclose(SWIGTYPE_p_jl_libhandle handle) {
    return Julia4JJNI.jl_dlclose(SWIGTYPE_p_jl_libhandle.getCPtr(handle));
  }

  public static int jl_dlsym(SWIGTYPE_p_jl_libhandle handle, String symbol, SWIGTYPE_p_p_void value, int throw_err) {
    return Julia4JJNI.jl_dlsym(SWIGTYPE_p_jl_libhandle.getCPtr(handle), symbol, SWIGTYPE_p_p_void.getCPtr(value), throw_err);
  }

  public static SWIGTYPE_p_jl_value_t jl_toplevel_eval(SWIGTYPE_p_jl_module_t m, SWIGTYPE_p_jl_value_t v) {
    long cPtr = Julia4JJNI.jl_toplevel_eval(SWIGTYPE_p_jl_module_t.getCPtr(m), SWIGTYPE_p_jl_value_t.getCPtr(v));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_toplevel_eval_in(SWIGTYPE_p_jl_module_t m, SWIGTYPE_p_jl_value_t ex) {
    long cPtr = Julia4JJNI.jl_toplevel_eval_in(SWIGTYPE_p_jl_module_t.getCPtr(m), SWIGTYPE_p_jl_value_t.getCPtr(ex));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_eval_string(String str) {
    long cPtr = Julia4JJNI.jl_eval_string(str);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_load_file_string(String text, long len, String filename, SWIGTYPE_p_jl_module_t module) {
    long cPtr = Julia4JJNI.jl_load_file_string(text, len, filename, SWIGTYPE_p_jl_module_t.getCPtr(module));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_load(SWIGTYPE_p_jl_module_t module, String fname) {
    long cPtr = Julia4JJNI.jl_load(SWIGTYPE_p_jl_module_t.getCPtr(module), fname);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_module_t jl_base_relative_to(SWIGTYPE_p_jl_module_t m) {
    long cPtr = Julia4JJNI.jl_base_relative_to(SWIGTYPE_p_jl_module_t.getCPtr(m));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_module_t(cPtr, false);
  }

  public static void jl_register_newmeth_tracer(SWIGTYPE_p_f_p_jl_method_t__void callback) {
    Julia4JJNI.jl_register_newmeth_tracer(SWIGTYPE_p_f_p_jl_method_t__void.getCPtr(callback));
  }

  public static SWIGTYPE_p_jl_value_t jl_copy_ast(SWIGTYPE_p_jl_value_t expr) {
    long cPtr = Julia4JJNI.jl_copy_ast(SWIGTYPE_p_jl_value_t.getCPtr(expr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_array_t jl_compress_ir(SWIGTYPE_p_jl_method_t m, SWIGTYPE_p_jl_code_info_t code) {
    long cPtr = Julia4JJNI.jl_compress_ir(SWIGTYPE_p_jl_method_t.getCPtr(m), SWIGTYPE_p_jl_code_info_t.getCPtr(code));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_array_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_code_info_t jl_uncompress_ir(SWIGTYPE_p_jl_method_t m, SWIGTYPE_p_jl_code_instance_t metadata, SWIGTYPE_p_jl_array_t data) {
    long cPtr = Julia4JJNI.jl_uncompress_ir(SWIGTYPE_p_jl_method_t.getCPtr(m), SWIGTYPE_p_jl_code_instance_t.getCPtr(metadata), SWIGTYPE_p_jl_array_t.getCPtr(data));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_code_info_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_compress_argnames(SWIGTYPE_p_jl_array_t syms) {
    long cPtr = Julia4JJNI.jl_compress_argnames(SWIGTYPE_p_jl_array_t.getCPtr(syms));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_array_t jl_uncompress_argnames(SWIGTYPE_p_jl_value_t syms) {
    long cPtr = Julia4JJNI.jl_uncompress_argnames(SWIGTYPE_p_jl_value_t.getCPtr(syms));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_array_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_uncompress_argname_n(SWIGTYPE_p_jl_value_t syms, long i) {
    long cPtr = Julia4JJNI.jl_uncompress_argname_n(SWIGTYPE_p_jl_value_t.getCPtr(syms), i);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static int jl_is_operator(String sym) {
    return Julia4JJNI.jl_is_operator(sym);
  }

  public static int jl_is_unary_operator(String sym) {
    return Julia4JJNI.jl_is_unary_operator(sym);
  }

  public static int jl_is_unary_and_binary_operator(String sym) {
    return Julia4JJNI.jl_is_unary_and_binary_operator(sym);
  }

  public static int jl_operator_precedence(String sym) {
    return Julia4JJNI.jl_operator_precedence(sym);
  }

  public static SWIGTYPE_p_jl_value_t jl_apply_generic(SWIGTYPE_p_jl_value_t F, SWIGTYPE_p_p_jl_value_t args, long nargs) {
    long cPtr = Julia4JJNI.jl_apply_generic(SWIGTYPE_p_jl_value_t.getCPtr(F), SWIGTYPE_p_p_jl_value_t.getCPtr(args), nargs);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_invoke(SWIGTYPE_p_jl_value_t F, SWIGTYPE_p_p_jl_value_t args, long nargs, SWIGTYPE_p_jl_method_instance_t meth) {
    long cPtr = Julia4JJNI.jl_invoke(SWIGTYPE_p_jl_value_t.getCPtr(F), SWIGTYPE_p_p_jl_value_t.getCPtr(args), nargs, SWIGTYPE_p_jl_method_instance_t.getCPtr(meth));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static int jl_invoke_api(SWIGTYPE_p_jl_code_instance_t linfo) {
    return Julia4JJNI.jl_invoke_api(SWIGTYPE_p_jl_code_instance_t.getCPtr(linfo));
  }

  public static SWIGTYPE_p_jl_value_t jl_call(SWIGTYPE_p_jl_function_t f, SWIGTYPE_p_p_jl_value_t args, long nargs) {
    long cPtr = Julia4JJNI.jl_call(SWIGTYPE_p_jl_function_t.getCPtr(f), SWIGTYPE_p_p_jl_value_t.getCPtr(args), nargs);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_call0(SWIGTYPE_p_jl_function_t f) {
    long cPtr = Julia4JJNI.jl_call0(SWIGTYPE_p_jl_function_t.getCPtr(f));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_call1(SWIGTYPE_p_jl_function_t f, SWIGTYPE_p_jl_value_t a) {
    long cPtr = Julia4JJNI.jl_call1(SWIGTYPE_p_jl_function_t.getCPtr(f), SWIGTYPE_p_jl_value_t.getCPtr(a));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_call2(SWIGTYPE_p_jl_function_t f, SWIGTYPE_p_jl_value_t a, SWIGTYPE_p_jl_value_t b) {
    long cPtr = Julia4JJNI.jl_call2(SWIGTYPE_p_jl_function_t.getCPtr(f), SWIGTYPE_p_jl_value_t.getCPtr(a), SWIGTYPE_p_jl_value_t.getCPtr(b));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_call3(SWIGTYPE_p_jl_function_t f, SWIGTYPE_p_jl_value_t a, SWIGTYPE_p_jl_value_t b, SWIGTYPE_p_jl_value_t c) {
    long cPtr = Julia4JJNI.jl_call3(SWIGTYPE_p_jl_function_t.getCPtr(f), SWIGTYPE_p_jl_value_t.getCPtr(a), SWIGTYPE_p_jl_value_t.getCPtr(b), SWIGTYPE_p_jl_value_t.getCPtr(c));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static void jl_install_sigint_handler() {
    Julia4JJNI.jl_install_sigint_handler();
  }

  public static void jl_sigatomic_begin() {
    Julia4JJNI.jl_sigatomic_begin();
  }

  public static void jl_sigatomic_end() {
    Julia4JJNI.jl_sigatomic_end();
  }

  public static SWIGTYPE_p_jl_typename_t jl_new_typename_in(SWIGTYPE_p_jl_sym_t name, SWIGTYPE_p_jl_module_t inmodule, int _abstract, int mutabl) {
    long cPtr = Julia4JJNI.jl_new_typename_in(SWIGTYPE_p_jl_sym_t.getCPtr(name), SWIGTYPE_p_jl_module_t.getCPtr(inmodule), _abstract, mutabl);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_typename_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_tvar_t jl_new_typevar(SWIGTYPE_p_jl_sym_t name, SWIGTYPE_p_jl_value_t lb, SWIGTYPE_p_jl_value_t ub) {
    long cPtr = Julia4JJNI.jl_new_typevar(SWIGTYPE_p_jl_sym_t.getCPtr(name), SWIGTYPE_p_jl_value_t.getCPtr(lb), SWIGTYPE_p_jl_value_t.getCPtr(ub));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_tvar_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_instantiate_unionall(SWIGTYPE_p_jl_unionall_t u, SWIGTYPE_p_jl_value_t p) {
    long cPtr = Julia4JJNI.jl_instantiate_unionall(SWIGTYPE_p_jl_unionall_t.getCPtr(u), SWIGTYPE_p_jl_value_t.getCPtr(p));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_apply_type(SWIGTYPE_p_jl_value_t tc, SWIGTYPE_p_p_jl_value_t params, long n) {
    long cPtr = Julia4JJNI.jl_apply_type(SWIGTYPE_p_jl_value_t.getCPtr(tc), SWIGTYPE_p_p_jl_value_t.getCPtr(params), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_apply_type1(SWIGTYPE_p_jl_value_t tc, SWIGTYPE_p_jl_value_t p1) {
    long cPtr = Julia4JJNI.jl_apply_type1(SWIGTYPE_p_jl_value_t.getCPtr(tc), SWIGTYPE_p_jl_value_t.getCPtr(p1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_apply_type2(SWIGTYPE_p_jl_value_t tc, SWIGTYPE_p_jl_value_t p1, SWIGTYPE_p_jl_value_t p2) {
    long cPtr = Julia4JJNI.jl_apply_type2(SWIGTYPE_p_jl_value_t.getCPtr(tc), SWIGTYPE_p_jl_value_t.getCPtr(p1), SWIGTYPE_p_jl_value_t.getCPtr(p2));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_datatype_t jl_apply_cmpswap_type(SWIGTYPE_p_jl_value_t dt) {
    long cPtr = Julia4JJNI.jl_apply_cmpswap_type(SWIGTYPE_p_jl_value_t.getCPtr(dt));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_datatype_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_apply_tuple_type(SWIGTYPE_p_jl_svec_t params, int check) {
    long cPtr = Julia4JJNI.jl_apply_tuple_type(SWIGTYPE_p_jl_svec_t.getCPtr(params), check);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_apply_tuple_type_v(SWIGTYPE_p_p_jl_value_t p, long np) {
    long cPtr = Julia4JJNI.jl_apply_tuple_type_v(SWIGTYPE_p_p_jl_value_t.getCPtr(p), np);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_datatype_t jl_new_datatype(SWIGTYPE_p_jl_sym_t name, SWIGTYPE_p_jl_module_t module, SWIGTYPE_p_jl_datatype_t _super, SWIGTYPE_p_jl_svec_t parameters, SWIGTYPE_p_jl_svec_t fnames, SWIGTYPE_p_jl_svec_t ftypes, SWIGTYPE_p_jl_svec_t fattrs, int _abstract, int mutabl, int ninitialized) {
    long cPtr = Julia4JJNI.jl_new_datatype(SWIGTYPE_p_jl_sym_t.getCPtr(name), SWIGTYPE_p_jl_module_t.getCPtr(module), SWIGTYPE_p_jl_datatype_t.getCPtr(_super), SWIGTYPE_p_jl_svec_t.getCPtr(parameters), SWIGTYPE_p_jl_svec_t.getCPtr(fnames), SWIGTYPE_p_jl_svec_t.getCPtr(ftypes), SWIGTYPE_p_jl_svec_t.getCPtr(fattrs), _abstract, mutabl, ninitialized);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_datatype_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_datatype_t jl_new_primitivetype(SWIGTYPE_p_jl_value_t name, SWIGTYPE_p_jl_module_t module, SWIGTYPE_p_jl_datatype_t _super, SWIGTYPE_p_jl_svec_t parameters, long nbits) {
    long cPtr = Julia4JJNI.jl_new_primitivetype(SWIGTYPE_p_jl_value_t.getCPtr(name), SWIGTYPE_p_jl_module_t.getCPtr(module), SWIGTYPE_p_jl_datatype_t.getCPtr(_super), SWIGTYPE_p_jl_svec_t.getCPtr(parameters), nbits);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_datatype_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_new_bits(SWIGTYPE_p_jl_value_t bt, SWIGTYPE_p_void src) {
    long cPtr = Julia4JJNI.jl_new_bits(SWIGTYPE_p_jl_value_t.getCPtr(bt), SWIGTYPE_p_void.getCPtr(src));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_atomic_new_bits(SWIGTYPE_p_jl_value_t dt, String src) {
    long cPtr = Julia4JJNI.jl_atomic_new_bits(SWIGTYPE_p_jl_value_t.getCPtr(dt), src);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static void jl_atomic_store_bits(String dst, SWIGTYPE_p_jl_value_t src, int nb) {
    Julia4JJNI.jl_atomic_store_bits(dst, SWIGTYPE_p_jl_value_t.getCPtr(src), nb);
  }

  public static SWIGTYPE_p_jl_value_t jl_atomic_swap_bits(SWIGTYPE_p_jl_value_t dt, String dst, SWIGTYPE_p_jl_value_t src, int nb) {
    long cPtr = Julia4JJNI.jl_atomic_swap_bits(SWIGTYPE_p_jl_value_t.getCPtr(dt), dst, SWIGTYPE_p_jl_value_t.getCPtr(src), nb);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static int jl_atomic_bool_cmpswap_bits(String dst, SWIGTYPE_p_jl_value_t expected, SWIGTYPE_p_jl_value_t src, int nb) {
    return Julia4JJNI.jl_atomic_bool_cmpswap_bits(dst, SWIGTYPE_p_jl_value_t.getCPtr(expected), SWIGTYPE_p_jl_value_t.getCPtr(src), nb);
  }

  public static SWIGTYPE_p_jl_value_t jl_atomic_cmpswap_bits(SWIGTYPE_p_jl_datatype_t dt, SWIGTYPE_p_jl_datatype_t rettype, String dst, SWIGTYPE_p_jl_value_t expected, SWIGTYPE_p_jl_value_t src, int nb) {
    long cPtr = Julia4JJNI.jl_atomic_cmpswap_bits(SWIGTYPE_p_jl_datatype_t.getCPtr(dt), SWIGTYPE_p_jl_datatype_t.getCPtr(rettype), dst, SWIGTYPE_p_jl_value_t.getCPtr(expected), SWIGTYPE_p_jl_value_t.getCPtr(src), nb);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_new_struct(SWIGTYPE_p_jl_datatype_t type) {
    long cPtr = Julia4JJNI.jl_new_struct(SWIGTYPE_p_jl_datatype_t.getCPtr(type));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_new_structv(SWIGTYPE_p_jl_datatype_t type, SWIGTYPE_p_p_jl_value_t args, long na) {
    long cPtr = Julia4JJNI.jl_new_structv(SWIGTYPE_p_jl_datatype_t.getCPtr(type), SWIGTYPE_p_p_jl_value_t.getCPtr(args), na);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_new_structt(SWIGTYPE_p_jl_datatype_t type, SWIGTYPE_p_jl_value_t tup) {
    long cPtr = Julia4JJNI.jl_new_structt(SWIGTYPE_p_jl_datatype_t.getCPtr(type), SWIGTYPE_p_jl_value_t.getCPtr(tup));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_new_struct_uninit(SWIGTYPE_p_jl_datatype_t type) {
    long cPtr = Julia4JJNI.jl_new_struct_uninit(SWIGTYPE_p_jl_datatype_t.getCPtr(type));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_method_instance_t jl_new_method_instance_uninit() {
    long cPtr = Julia4JJNI.jl_new_method_instance_uninit();
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_method_instance_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_svec_t jl_svec(long n) {
    long cPtr = Julia4JJNI.jl_svec(n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_svec_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_svec_t jl_svec1(SWIGTYPE_p_void a) {
    long cPtr = Julia4JJNI.jl_svec1(SWIGTYPE_p_void.getCPtr(a));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_svec_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_svec_t jl_svec2(SWIGTYPE_p_void a, SWIGTYPE_p_void b) {
    long cPtr = Julia4JJNI.jl_svec2(SWIGTYPE_p_void.getCPtr(a), SWIGTYPE_p_void.getCPtr(b));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_svec_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_svec_t jl_alloc_svec(long n) {
    long cPtr = Julia4JJNI.jl_alloc_svec(n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_svec_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_svec_t jl_alloc_svec_uninit(long n) {
    long cPtr = Julia4JJNI.jl_alloc_svec_uninit(n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_svec_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_svec_t jl_svec_copy(SWIGTYPE_p_jl_svec_t a) {
    long cPtr = Julia4JJNI.jl_svec_copy(SWIGTYPE_p_jl_svec_t.getCPtr(a));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_svec_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_svec_t jl_svec_fill(long n, SWIGTYPE_p_jl_value_t x) {
    long cPtr = Julia4JJNI.jl_svec_fill(n, SWIGTYPE_p_jl_value_t.getCPtr(x));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_svec_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_sym_t jl_symbol(String str) {
    long cPtr = Julia4JJNI.jl_symbol(str);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_sym_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_sym_t jl_symbol_lookup(String str) {
    long cPtr = Julia4JJNI.jl_symbol_lookup(str);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_sym_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_sym_t jl_symbol_n(String str, long len) {
    long cPtr = Julia4JJNI.jl_symbol_n(str, len);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_sym_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_sym_t jl_gensym() {
    long cPtr = Julia4JJNI.jl_gensym();
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_sym_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_sym_t jl_tagged_gensym(String str, long len) {
    long cPtr = Julia4JJNI.jl_tagged_gensym(str, len);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_sym_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_sym_t jl_get_root_symbol() {
    long cPtr = Julia4JJNI.jl_get_root_symbol();
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_sym_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_method_t jl_method_def(SWIGTYPE_p_jl_svec_t argdata, SWIGTYPE_p_jl_methtable_t mt, SWIGTYPE_p_jl_code_info_t f, SWIGTYPE_p_jl_module_t module) {
    long cPtr = Julia4JJNI.jl_method_def(SWIGTYPE_p_jl_svec_t.getCPtr(argdata), SWIGTYPE_p_jl_methtable_t.getCPtr(mt), SWIGTYPE_p_jl_code_info_t.getCPtr(f), SWIGTYPE_p_jl_module_t.getCPtr(module));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_method_t(cPtr, false);
  }

  public static long jl_get_world_counter() {
    return Julia4JJNI.jl_get_world_counter();
  }

  public static SWIGTYPE_p_jl_value_t jl_box_bool(byte x) {
    long cPtr = Julia4JJNI.jl_box_bool(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_int8(byte x) {
    long cPtr = Julia4JJNI.jl_box_int8(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_uint8(short x) {
    long cPtr = Julia4JJNI.jl_box_uint8(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_int16(short x) {
    long cPtr = Julia4JJNI.jl_box_int16(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_uint16(int x) {
    long cPtr = Julia4JJNI.jl_box_uint16(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_int32(int x) {
    long cPtr = Julia4JJNI.jl_box_int32(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_uint32(long x) {
    long cPtr = Julia4JJNI.jl_box_uint32(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_char(long x) {
    long cPtr = Julia4JJNI.jl_box_char(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_int64(long x) {
    long cPtr = Julia4JJNI.jl_box_int64(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_uint64(java.math.BigInteger x) {
    long cPtr = Julia4JJNI.jl_box_uint64(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_float32(float x) {
    long cPtr = Julia4JJNI.jl_box_float32(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_float64(double x) {
    long cPtr = Julia4JJNI.jl_box_float64(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_voidpointer(SWIGTYPE_p_void x) {
    long cPtr = Julia4JJNI.jl_box_voidpointer(SWIGTYPE_p_void.getCPtr(x));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_uint8pointer(SWIGTYPE_p_unsigned_char x) {
    long cPtr = Julia4JJNI.jl_box_uint8pointer(SWIGTYPE_p_unsigned_char.getCPtr(x));
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_ssavalue(long x) {
    long cPtr = Julia4JJNI.jl_box_ssavalue(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static SWIGTYPE_p_jl_value_t jl_box_slotnumber(long x) {
    long cPtr = Julia4JJNI.jl_box_slotnumber(x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_jl_value_t(cPtr, false);
  }

  public static byte jl_unbox_bool(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_bool(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static byte jl_unbox_int8(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_int8(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static short jl_unbox_uint8(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_uint8(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static short jl_unbox_int16(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_int16(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static int jl_unbox_uint16(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_uint16(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static int jl_unbox_int32(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_int32(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static long jl_unbox_uint32(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_uint32(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static long jl_unbox_int64(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_int64(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static java.math.BigInteger jl_unbox_uint64(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_uint64(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static float jl_unbox_float32(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_float32(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static double jl_unbox_float64(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_float64(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static SWIGTYPE_p_void jl_unbox_voidpointer(SWIGTYPE_p_jl_value_t v) {
    long cPtr = Julia4JJNI.jl_unbox_voidpointer(SWIGTYPE_p_jl_value_t.getCPtr(v));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_char jl_unbox_uint8pointer(SWIGTYPE_p_jl_value_t v) {
    long cPtr = Julia4JJNI.jl_unbox_uint8pointer(SWIGTYPE_p_jl_value_t.getCPtr(v));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static int jl_get_size(SWIGTYPE_p_jl_value_t val, SWIGTYPE_p_size_t pnt) {
    return Julia4JJNI.jl_get_size(SWIGTYPE_p_jl_value_t.getCPtr(val), SWIGTYPE_p_size_t.getCPtr(pnt));
  }

  public static String jl_unbox_string(SWIGTYPE_p_jl_value_t v) {
    return Julia4JJNI.jl_unbox_string(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

  public static void jl_show(SWIGTYPE_p_jl_value_t v) {
    Julia4JJNI.jl_show(SWIGTYPE_p_jl_value_t.getCPtr(v));
  }

}
