/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.julia.jni.swig;

public class SWIGTYPE_p_f_p_jl_method_t__void {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_jl_method_t__void(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_jl_method_t__void() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_jl_method_t__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_f_p_jl_method_t__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

